sudo: required

group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-carbon-c-relay .
  - docker run --detach --name grafana bodsch/docker-carbon-c-relay

script:
  - docker ps | grep -q carbon-c-relay

